[package]
name = "picomet-lang-runtime"
version = "0.1.0"
authors = ["vain0x <vainzerox@gmail.com>"]
edition = "2015"
build = "src/build.rs"

[dependencies]
picomet-lang-compiler = { path = "../compiler" }

[build-dependencies]
picomet-lang-compiler = { path = "../compiler" }
